### ISSUE TITLE
"3 months of Stay at home (strict compliance)" model doesn't seem to match description

### ISSUE THREAD

**Issue by embreinhardt** [covid-projections/covid-data-model#120]
From the [model reference](https://data.covidactnow.org/Covid_Act_Now_Model_References_and_Assumptions.pdf), the shelter in place model makes these R assumptions: "1.3 for 4 weeks, 1.1 for 4 weeks, 0.8 for 4 weeks."

However the results for the "3 months of Stay at home (strict compliance)" model appear to temporarily _accelerate_ after each assumed decrease in R, rather than start declining. This appears to be true in each county and state level model (while all examples screenshotted are in CA, this appears true across every state I've checked). 

![Screen Shot 2020-04-05 at 8 55 42 PM](https://user-images.githubusercontent.com/2966080/78521774-d5d0bc00-777f-11ea-86cc-f5d05b30f13e.png)

![Screen Shot 2020-04-05 at 8 49 26 PM](https://user-images.githubusercontent.com/2966080/78521597-37dcf180-777f-11ea-9138-a72472ae3ee1.png)

![Screen Shot 2020-04-05 at 8 49 03 PM](https://user-images.githubusercontent.com/2966080/78521600-390e1e80-777f-11ea-8c32-597ca758c453.png)

**Comment by davidstrauss** [comment]
Apologies for the delayed response, but we've substantially improved our approach to modeling since you sent your concerns. The changes reworked how interventions get applied, and I believe they should have addressed your concerns.

I'm closing this for now, but please feel free to re-open if we haven't adequately addressed this.
