### ISSUE TITLE
Support Inference Output for counties

### ISSUE THREAD

**Issue by goldblatt** [covid-projections/covid-data-model#258]
Context: https://github.com/covid-projections/covid-data-model/pull/260.
We should remove `if intervention in Intervention.county_supported_interventions():` once we support counties intervention

**Comment by mikelehen** [comment]
This is going to block us moving the website over to the new API endpoints. 😢 

Per Susan, I believe we need to remove the check here: https://github.com/covid-projections/covid-data-model/blob/08605b09ac7dc1facef825c274fdbd70b0f3eb71/cli/run_counties_api.py#L41

But then add in some mechanism for it to detect the presence of the inference results (i.e. the `.2.json` file) or not (since some counties have inference results and some don't).
