### ISSUE TITLE
JHUDataset county aggregation bug.

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#27]
There's an issue where dates that have county data but not state data don't properly aggregate up correctly.

As a simple side-effect of this,  if you run:
```
model_state('USA', 'CA', INTERVENTIONS[0])
```
then the results start with 2020-03-10 instead of 2020-03-03 because the prior dates only have county data.

**Comment by tsebens** [comment]
Resolved. The problem was that the backfill was occurring before the cutoff, but the backfill was looking for the earliest date in the data to start backfilling from. If there was a data point from, say jan21, then the backfill would think it didn't need to do anything, then the cutoff would remove that data and reveal a gap between mar3 andmar10.
