### ISSUE TITLE
cumulativePositiveTests and cumulativeNegativeTests are not required

### ISSUE THREAD

**Issue by amrsalah-acc** [covid-projections/covid-data-model#351]
Hi Guys, 
There are two attributes they seem to be not required and can be reconciled 
As long as we have the "cumulativeConfirmedCases" , the following attributes become confusing and duplicate values with "cumulativePositiveTests" , however the following two attributes can be merged together as total number of tests (cumulativePositiveTest + cumulativeNegativeTests )

Thanks,
Amr Salah
MuleSoft

**Comment by PanditPranav** [comment]
Hey @amrsalah-acc,
Do you know what happened to those columns (negative and positive tests)?  I have been getting consistently null values for those columns since the migration of APIs... especially when I look into the actualsTimeSeries. 
`https://api.covidactnow.org/v2/county/{fips}.timeseries.json?apiKey={apiKey}`
