### ISSUE TITLE
No longer get static interventions for ~1000+ counties

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#371]
With the code currently in master, this check that we have at least 1800 counties is failing, because we only have 1003:

https://github.com/covid-projections/covid-data-model/blob/720dbf763d22d8907ee83691bd6cc296a03e4a0f/libs/validate_results.py#L99

> DataExportException
('counties.SELECTED_INTERVENTION', 'Expected more counties in the output, only found 1003')

I'm changing the threshold to 800 for now, but we need to figure out if this was an expected consequence of changes @erccarls made, and if so, if that's okay (it means we will show data for many fewer counties on the website, I believe).

**Comment by igorkofman** [comment]
I suspect this is ~expected and the fix is going to be a nicer “no data” page for counties .  Basically 50% of counties don’t have enough data to run inference and we now use “past inference” in all static models.   Longer term we can use api actuals to fill in some data in those counties but we’ll have to decide whether surfacing eg. Rt in a county with <50 total cases (the current cutoff) even makes sense.

**Comment by erccarls** [comment]
Yes, this is expected.  We can get the number back up shortly as we can both lower the thresholds and more data is coming in daily.  Right now we felt it was more prudent to reduce the number shipped until we can patch up a few things (especially moving to R_t based interventions which I should get to tomorrow).

**Comment by mikelehen** [comment]
Thanks! Closing since we seem to be moving forward with this!
