### ISSUE TITLE
OBSERVED_INTERVENTION has 10 fewer days in timeseries

### ISSUE THREAD

**Issue by mikelehen** [covid-projections/covid-data-model#377]
If you fetch:
* https://data.covidactnow.org/snapshot/208/us/states/ME.NO_INTERVENTION.timeseries.json
* https://data.covidactnow.org/snapshot/208/us/states/ME.OBSERVED_INTERVENTION.timeseries.json

The NO_INTERVENTION one starts on 2020-03-03 but the OBSERVED_INTERVENTION one starts on 2020-03-13.

I don't know why they're different or which one is "right", but presumably all the API endpoints should give the same date range.

**Comment by ghop02** [comment]
I wonder if this is because of the different inference techniques - i.e "no intervention" used the traditional backfilling while "Observed intervention" uses the new backfilling technique (what should we call that?),
with snapshot 231 (where they both use the new technique), they start on the same date (3/7 for some reason)

**Comment by mikelehen** [comment]
Oh, cool, thanks!  I should have checked 231.  I'll go ahead and close this then.  Though I am still a bit curious exactly where that start date is coming from and if we should be a bit more deliberate about it (since it's theoretically part of our API contract).
