### ISSUE TITLE
Maine Positive Cases Percentage

### ISSUE THREAD

**Issue by alyssad312** [covid-projections/covid-data-model#387]
It appears the data for Maine is not nearly correct. Their current positive percentage is ~5% while the model shows 20%.

**Comment by mikelehen** [comment]
@alyssad312 Thanks for flagging this.  This is an artifact of the way Maine has been reporting their tests.  They only report test negatives once a week. See raw underlying data here: https://covidtracking.com/data/state/maine#historical

This means their test positive rate is 100% for 6 days, and then drops when they report all their negatives.

We are planning to tweak our calculation to sum the last 7 days of cumulatives before calculating test positive rate which should compensate for this.  That issue is tracked here https://github.com/covid-projections/covid-projections/issues/706

Thanks!
