### ISSUE TITLE
Download indicators?

### ISSUE THREAD

**Issue by mgincnj** [covid-projections/covid-data-model#575]
I've been looking at indicators for a while, and was pleased to see that you are publishing them state by state.  As far as I'm aware, you're the only place that's publishing Contacts Traced.  Disappointed that there doesn't appear to be any way to download them via your API.  Any plans to do that?

That said, I see that you've just added Daily New Cases.  The issue I have is that many of the worst impacted states aren't testing enough.  If the positive test rate is flat or falling, fewer tests results in a lower daily new cases number irrespective of what's going on.  Seems to me that some combination of Testing Rate per 100K, positive test rate, and whether positive test rate is increasing, decreasing, or about the same, is more useful than Daily New Cases.

For example, AZ is testing only a little more than 1000 tests/100k last week and the count was down week over week; most other badly impacted states were testing at 1,500 - 2,000/100k.  The best states are well above 2,000.  This means that AZ's new case rate, while horrendous, appeared to be dropping, when in fact it was almost certainly increasing.
![Testing Rate vs  Positivity](https://user-images.githubusercontent.com/7313692/88564856-c1038700-d001-11ea-9b85-90f22428b440.jpg)

**Comment by BrettBoval** [comment]
Hi. 

- We work with Test and Trace for contact tracing https://testandtrace.com/state-data/. Our partnerships team works with them to update values when we find new/updated sources of data.
- We agree that Daily New Cases per 100k is dependent on testing, which is why we keep the test positivity metric too. The description for Arizona under test positivity reads:

> Positive test rate
ARIZONA
A relatively high percentage (20.7%) of COVID tests were positive, which indicates that testing in Arizona is limited and that most cases likely go undetected. At these levels, it is hard to know how fast COVID is actually spreading, and there is very high risk of being surprised by a wave of disease. More testing urgently needed.

I think that is consistent with your intuition too.

Best,
Brett
