### ISSUE TITLE
Missing counties?

### ISSUE THREAD

**Issue by infamousdanno** [covid-projections/covid-data-model#597]
I noticed when using the API that certain counties appear to be missing, but are present through the web page.  For example:

https://data.covidactnow.org/latest/us/counties/36005.WEAK_INTERVENTION.json
https://data.covidactnow.org/latest/us/counties/36047.WEAK_INTERVENTION.json

vs 

https://www.covidactnow.org/us/ny/county/kings_county?s=819151
https://www.covidactnow.org/us/ny/county/bronx_county?s=819151

**Comment by ghop02** [comment]
Hi! for New York City all of the data is actually aggregated into the ny county fips (36061).  so, you should be able to find results for:
https://data.covidactnow.org/latest/us/counties/36061.WEAK_INTERVENTION.json.

We aggregate Kings County, Queens, Bronx, and Richmond, and New York City.  a large part of this is due to [how the data is reported](https://github.com/nytimes/covid-19-data#geographic-exceptions)

**Comment by infamousdanno** [comment]
That explains it.  Thanks!
